### PR TITLE
Use ns.cmake for cmake

### PR DESCRIPTION
**Pull request by ccharly**

### CODE REVIEW

**Comment by jfalcou** [comment]
One small "issue" is this : 

    CMake Warning:
      Manually-specified variables were not used by the project:
        IS_TRAVIS_CI

**Comment by ccharly** [comment]
ah damn it! I'm on it. Thanks ;)

**Comment by ccharly** [comment]
How is this possible? There are some lines like:

```
if (NOT DEFINED IS_TRAVIS_CI)
```

So.. This is technically used anyway?

**Comment by ccharly** [comment]
Ok, it is gone now, I've gonna squish everything again and force push.

**Pull request merged**
